/**
 * This file was generated by the JPA Modeler
 */ 

package domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.ws.rs.FormParam;

/**
 * @author BGH43766
 */

@Entity
public class Person implements Serializable { 

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @FormParam("id")
    private Long id;

    @Basic
    @FormParam("firstName")
    private String firstName;

    @Basic
    @FormParam("lastName")
    private String lastName;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


}
